### PR TITLE
Course Select Card Improvements

### LINKED ISSUE #172: Course Select Card improvements
Right now `ExpandedCourseCard` calls the `fetch` to retrieve all of the sections from `api/sections`, and if you collapse then expand the card it will fetch again even though all of the data remains the same.

In order to fix this, we need to shift the fetching over to the parent `CourseCard` component so we don't make unneeded API calls.

### PR DESCRIPTION
**Pull request by firejake308**
* Fixed font of header buttons
* Clicking anywhere on the header now expands/collapses
* changed remove icon to trash can for consistency

### CODE REVIEW

**Comment by firejake308** [comment]
Both Ryan and Edgar pointed out that they expected clicking anywhere on the header to expand the course cards, so I went ahead and implemented that. I assume that collapsing should work the same, but I definitely want y'all to check how that feels before we finalize it

**Comment by gannonprudhomme** [comment]
Honestly, I say we do #186 in a different PR, as I like how we've been keeping a few of these PR's really small, as they're really easy to review & merge in a short amount of time (which we have struggled at in the past)

**Comment by gannonprudhomme** [comment]
But this works fine on my end, functions exactly how I'd expect it. My only comment would be we might want the ability to remove the course cards when they're collapsed, but I'm not sure what we would do with the text so I think it's fine if we add it at a later date

**Comment by firejake308** [comment]
I've added the remove icon in the collpased card. Does the positioning make sense?

**Comment by gannonprudhomme** [comment]
Oh lmao idk why I didn't think about that, that makes total sense 👍

**Pull request merged**
