### PR TITLE
Fixed bug where changing web would update honors instead

### PR DESCRIPTION
**Pull request by firejake308**
Quick bugfix cuz I forgot to update something when I created the BasicOptionRow component

### CODE REVIEW

**Comment by gannonprudhomme** [comment]
We should probably add a test that tests whatever functionality was broken so this doesn't happen again, as the tests should've caught this bug

**Comment by firejake308** [comment]
Added tests. Please note that accurate testing required adding a new library that more actively mocks click events.

**Comment by firejake308** [comment]
Lmao I did them in a new file and forgot to `git add` it

**Comment by firejake308** [comment]
Oops, I had the changes in a separate file that I forgot to `git add`. I also accidentally wiped the file by checking out a different branch, so it'll take me a minute to rewrite the tests

**Comment by firejake308** [comment]
There we go. This'll be a squash and merge if y'all approve of how the tests are done

**Comment by firejake308** [comment]
Rebased with master, should be up-to-date as of 5/10

**Pull request merged**
