### PR TITLE
Frontend/rename web remote

### LINKED ISSUE #395: Change references of "web" to "remote"
Given that we're adding `asynchronous` usage to the website, we should change any instances of our site of `web` to `remote` just to be more precise. I could be convinced to to leave it with web (or even change it to online), but given the rise of asynchronous classes I think it's worth being precise

### PR DESCRIPTION
**Pull request by eelyort**
## Description

Renames all references of 'web' to 'remote' for clarity purposes.

## How to test

Automated tests have all been refactored. Otherwise look at the basic select and "web" should be replaced with "remote."

## Screenshots

image

## Related tasks

Closes #395

### CODE REVIEW

**Comment by eelyort** [comment]
Did the cherry picking

**Comment by gannonprudhomme** [comment]
Can you merge master into this now that #417 and #444 are merged

**Comment by eelyort** [comment]
I merged this branch with master

**Review by gannonprudhomme — APPROVED** [review]
Thanks for doing this! Remember to squash and merge

**Pull request merged**
