### PR TITLE
Made Add Course button sticky

### PR DESCRIPTION
**Pull request by firejake308**
A lot of our users were confused by the positioning of our Add Course button. This PR puts the Add course button right below the last course card, but makes the button "sticky" so that it can't go below the bottom of the CourseSelectColumn. Make sure that the spacing looks right to y'all

### CODE REVIEW

**Comment by gannonprudhomme** [comment]
Couldn't this just be merged into master?

**Comment by firejake308** [comment]
My thoughts were to have y'all review it here so that you can see how it looks on the complete scheduling page, and then rebase it onto master

**Comment by gannonprudhomme** [comment]
I think you should remove the `row:last-of-type { padding-bottom: 0 }` from `CourseSelectColumn.css` so that the Add Course button doesn't touch the last course card. 

Likewise, I have no idea how it would be done but if we could make it so that when it's at the bottom of the page it acts like it did before this PR (static at the bottom of the page), so it doesn't move up when we scroll all the way to the bottom I think this would be perfect

add course sticky

**Comment by firejake308** [comment]
Removing the `last-of-type` rule helped quite a bit, and I just got rid of the button's marginBottom to fix the slight scroll at the end.

**Comment by firejake308** [comment]
Rebased onto master

**Comment by ThatJuanGuy** [comment]
If I go to localhost nothing shows up. How do I see the changes on the website?

**Comment by firejake308** [comment]
Yeah, you can't see the changes right now, but the way I had it originally
included the commits for the scheduling page, so you could. Noww that I've
rebased it onto master, uhhhh, you could try to rebase onto
`frontend/scheduling-page`, or maybe just wait until we review that PR and
look at it later

>

**Comment by firejake308** [comment]
@ThatJuanGuy Actually, go to http://localhost:8000/test

**Comment by ThatJuanGuy** [comment]
Ok. I tried but I keep getting this blank page. blankschedulerpage
I also tried http://localhost:8000/test/ with the slash a the end just in case.

**Comment by ThatJuanGuy** [comment]
Is there something I'm missing?

**Comment by gannonprudhomme** [comment]
Have you run `npm run build`?

**Comment by firejake308** [comment]
Did you run `npm run dev` in `autoscheduler/frontend/src`? If so, open your console with F12. There should hopefully be an error message there or something

**Comment by ThatJuanGuy** [comment]
No I did not. I am doing that now.

**Comment by ThatJuanGuy** [comment]
It worked a lot better but unless it's just a header bar (which I'm pretty sure it isn't), it's still not working. I pulled from the origin and got some modifications but don't know if I should commit them or not. What I was trying to do to run it was the following.
1. Open github desktop
2. Pull the PR and open it in vscode
3. go to `autoscheduler/frontend/src` and run `npm run dev`
4. open new terminal and go to `autoscheduler/` and run `python manage.py runserver`.
5. go to http://localhost:8000/test and hope something shows up.
I wasn't getting any error messages with this method as far as I could tell though so I pulled again thinking maybe it was because I was using old code or something. I now have 20 merge conflicts. If I try to do `npm run dev` with the merge conflicts it gives me errors in `[./redux/reducer.ts] 1.03 KiB {main} [built] [4 errors]`. Do I accept all the changes and try again? All the error messages are either  `Merge conflict marker encountered.` or `Cannot find name '(name goes here)'.`.

**Comment by gannonprudhomme** [comment]
@ThatJuanGuy Join the Discord voice when you can, I'll join and walk you through it

**Comment by ThatJuanGuy** [comment]
Minor issue but I would like the small gray padding at the top of the button (see image below) to stay there when you scroll up on the page for purely cosmetic purposes.
blankschedulerpage
Currently, the button just overlaps with whatever and it looks a little bit weird if it only has padding when its below all the course cards.
blankschedulerpagenopad
It also makes the button a bit harder to find if it is overlapping a maroon colored tab and could lead to accidentally collapsing/expanding or removing a course card because the buttons overlap, although accidental removal is highly unlikely as that function seems to be confined to the very left corner
blankschedulerpage

**Comment by firejake308** [comment]
@ThatJuanGuy This is a bit hacky, as it makes an 8px gray border on top of the button rather than making it truly transparent, but I think it achieves the feel you wanted. Would you agree?

**Comment by ThatJuanGuy** [comment]
Yes. Looks Great!

**Comment by gannonprudhomme** [comment]
Seems like it was always like this, but do we not want the course card & add course button to be the same width when there is no scroll bar? (I set the `.container`'s width to `30%` in `CourseSelectColumn.css` just for testing, but it happens regardless)

chrome_ZEtS2rm1cP
chrome_jDdTCfSuVv

**Comment by firejake308** [comment]
@gannonprudhomme Fixed the padding thing, lmk if anything else needs to be fixed

**Pull request merged**
