### PR TITLE
Fixie wixe da PW tempwate UwU

### PR DESCRIPTION
**Pull request by firejake308**
## Descwiption

Pwease descwibe what the puww wequest is achieving. （\*＾-＾*）

## Wationyawe

If nyecessawy, defend any changes that senpai made. (ง •_•)ง

## Hau too testie-westie youw fixie-wixie

Descwibe the best way to test the specific changes senpai made. If it's cuvwing a speciaw case,
make suwe to incwude the situations they shouwd check out (i.e. PHYS 207 - 501, tewm 202031)
ψ(._. )>

## Scweenshots

If it's a fwontend change, pwovide scweenshots of it. If possibwe, show the change on diffewent
wesowutions/sizes. (。・ω・。)

If you'we changing a existing fwontend wook, pwovide a befowe and aftew scweenshot in the tabwe bewow.

|Befowe|Aftew|
|--|--|
|Befowe Scweenshot|Aftew Scweenshot|

## Wewated tasks

Cwosing tag. Don't fowget to wink the issue w/ the PW in ZenHub at the bottom. ༼ つ ◕_◕ ༽つ

Inspiwed by this [PR](https://github.com/blueman-project/blueman/issues/1110)

### CODE REVIEW

**Comment by TerrorBite** [comment]
I'm just here to see what the reviewers say.

**Comment by ryan-conn** [comment]
Don't mind me, just dealing with this PR
image

**Comment by gannon-eero** [comment]
Why would you do this to us

**Comment by bennyman123abc** [comment]
Wake me when a reviewer sets fire to the repo over this

**Comment by UwUnyaa** [comment]
LGTM

**Comment by Space-Walrus** [comment]
GikobTt

**Comment by Space-Walrus** [comment]
Weebs out

**Pull request closed without merging**
