### PR TITLE
Fix redundant course search take 2

### LINKED ISSUE #172: Course Select Card improvements
Right now `ExpandedCourseCard` calls the `fetch` to retrieve all of the sections from `api/sections`, and if you collapse then expand the card it will fetch again even though all of the data remains the same.

In order to fix this, we need to shift the fetching over to the parent `CourseCard` component so we don't make unneeded API calls.

### PR DESCRIPTION
**Pull request by firejake308**
I just made a new branch to fix the incorrect rebase from #201 

The fix required updating Material UI, so you'll have to rerun `npm install`. Also, be on the lookout for any breaking changes. One minor bug I've noticed is that the autocomplete menu is sometimes misplaced for some reason, but it seems to be fixed when there are 2 course cards.

TODO automatically select if the user types the exact course

Closes #172

### CODE REVIEW

**Comment by gannonprudhomme** [comment]
You mean to merged this into `frontend/course-card-route-connection`, right?

**Comment by firejake308** [comment]
Yeah, just realized that. Also rebased again to get it to have just the one commit that I added

**Comment by firejake308** [comment]
Btw, if you want to get the linting to pass, I'm pretty sure reading onto the current master should take care of it

**Comment by firejake308** [comment]
And for the tests, you'll have to mock fetch in order to get that passing

**Pull request merged**
